server:
  port: 8020
spring:
  application:
    name: penguin-config
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name} # 注册到consul的服务名称
    config:
      label: master  # git仓库分支
      server:
        git:
          uri: https://github.com/AdvancedSoftwareDesignAndImplementation/penguin-go-spring-cloud  # 配置git仓库的地址
          search-paths: config-repository  # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:  # git仓库的账号
          password:  # git仓库的密码
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:  # 接口开放相关配置
  endpoints:
    web:
      exposure:
        include: "*"