server:
  port: 8005
spring:
  application:
    name: penguin-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}	# 注册到consul的服务名称
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  zipkin:
    base-url: http://localhost:9411/  # http://localhost:9411/或者根据docker中的实际地址
    sender: 
      type: web # zipkin无法看到client信息的解决方案
  sleuth:
    sampler:
      probability: 1 # 样本采集量，默认为0.1，为了测试这里修改为1，正式环境一般使用默认值
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#开启熔断器
feign:
  hystrix:
    enabled: true